baseURL = "https://zoe4everyang.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Zoe Yang"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80


[params]
title = "I'm Zoe Yang"
author = "Zoe Yang"
description = "Call me Zoe"
profilePicture = "images/profile.jpg"
doNotLoadAnimations = true # Animations are loaded by default
contentratio = 0.6
# hidesidebar = true

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/ziyi-zoe-yang-0a68bb172/"
[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/zoe4everyang"
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:344769005@qq.com"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Work Experiences"
  weight = 300
  identifier = "work experiences"
  url = "/workexp/"

  [[menu.main]]
  name = "portfolio"
  weight = 400
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "gallery"
  weight = 500
  identifier = "gallery"
  url = "/gallery/"

  [[menu.main]]
  name = "CV"
  weight = 600
  identifier = "cv"
  url = "/cv/"

  [[menu.main]]
  name = "contact"
  weight = 700
  identifier = "contact"
  url = "/contact/"


[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false
